import sys
import os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import supabase

CATEGORIES = [
    ("MATH", "Mathematics", "#5577ee", 1),
    ("SCI", "Science", "#44bb88", 2),
    ("CS", "Computing", "#ee8833", 3),
    ("ENG", "Eng Tools", "#8899bb", 4),
    ("ME", "Mechanical", "#3399ff", 5),
    ("EE", "Electrical", "#ffcc33", 6),
    ("CE", "Civil", "#55cc77", 7),
    ("CHE", "Chemical", "#ff5555", 8),
    ("AERO", "Aerospace", "#9966ff", 9),
    ("BME", "Biomedical", "#ff55aa", 10),
    ("ENVE", "Environmental", "#44ccaa", 11),
    ("IE", "Industrial", "#ff9944", 12),
    ("MAT", "Materials", "#99cc44", 13),
    ("NUKE", "Nuclear", "#ffaa44", 14),
    ("ROB", "Robotics", "#44bbff", 15),
    ("CRED", "Credentials", "#c8a84b", 16),
]

NODES = [
    ("f_counting", "Counting & Number Sense", 0, "MATH", 10, 5, "elem",
     "Recognition of quantities, ordering, and basic number relationships. The absolute starting point for all quantitative reasoning.",
     "Count, compare, and order integers up to 1,000,000. Understand place value."),
    ("f_addition", "Basic Addition", 0, "MATH", 15, 8, "elem",
     "Single and multi-digit addition including carrying. Foundation for all arithmetic.",
     "Add multi-digit numbers with and without carrying. Complete 30 problems in 3 minutes."),
    ("f_subtraction", "Basic Subtraction", 0, "MATH", 15, 8, "elem",
     "Single and multi-digit subtraction including borrowing.",
     "Subtract multi-digit numbers with and without borrowing accurately."),
    ("f_multiplication", "Multiplication", 0, "MATH", 25, 12, "elem",
     "Times tables through 12, long multiplication, and understanding multiplication as repeated addition.",
     "Recite all times tables instantly. Multiply 4-digit by 3-digit numbers accurately."),
    ("f_division", "Division", 0, "MATH", 20, 10, "elem",
     "Long division, remainders, and the relationship between division and multiplication.",
     "Perform long division with remainder. Connect division to fractions."),
    ("f_fractions", "Fractions & Decimals", 0, "MATH", 30, 15, "elem",
     "Equivalent fractions, mixed numbers, operations on fractions, and conversion between fractions and decimals.",
     "Add, subtract, multiply and divide fractions and mixed numbers. Convert between fraction/decimal/percentage."),
    ("f_negative", "Negative Numbers & Integers", 0, "MATH", 20, 10, "middle",
     "Number line, absolute value, and arithmetic with negative numbers. Essential for understanding signed quantities in physics and engineering.",
     "Perform all four operations with negative integers. Evaluate absolute value expressions."),
    ("f_ratios", "Ratios & Proportional Reasoning", 0, "MATH", 25, 12, "middle",
     "Ratios, rates, unit conversion, and proportional relationships. Used constantly in dimensional analysis and engineering calculations.",
     "Solve proportion problems and unit conversions. Interpret ratios in context."),
    ("f_percentages", "Percentages", 0, "MATH", 20, 10, "middle",
     "Percentage calculations, percent change, and percentage of a quantity.",
     "Calculate percentage of a value, percent change, and reverse-percentage problems."),
    ("f_algebra1", "Algebra I", 0, "MATH", 60, 20, "middle",
     "Variables, linear equations and inequalities, systems of equations, and introduction to functions. The gateway to all engineering mathematics.",
     "Solve linear equations/inequalities. Graph lines. Solve 2×2 systems by substitution and elimination."),
    ("f_geometry", "Geometry — Foundations", 0, "MATH", 50, 18, "middle",
     "Euclidean geometry, proofs, congruence, similarity, coordinate geometry, and area/volume formulas. Underpins structural analysis and CAD.",
     "Write geometric proofs. Calculate area and volume for all standard shapes. Apply Pythagorean theorem."),
    ("f_logic", "Logic & Deductive Reasoning", 0, "MATH", 25, 8, "middle",
     "Boolean logic, truth tables, proof structures, and systematic problem-solving. Underpins digital logic, algorithm design, and engineering methodology.",
     "Construct and evaluate truth tables. Write simple formal proofs. Identify logical fallacies."),
    ("f_stats_basic", "Introductory Statistics & Probability", 0, "MATH", 40, 15, "middle",
     "Descriptive statistics, basic probability, distributions, and hypothesis testing. Needed for quality control, reliability engineering, and experimental design.",
     "Calculate mean, variance, standard deviation. Apply basic probability rules. Interpret normal distributions."),
    ("f_sci_method", "Scientific Method & Lab Skills", 0, "SCI", 20, 8, "middle",
     "Experimental design, measurement, error analysis, and lab documentation. Forms the basis of engineering experimentation.",
     "Design a controlled experiment. Perform error propagation calculations. Document results to publication standard."),
    ("f_comp_basics", "Computer Basics", 0, "CS", 20, 6, "middle",
     "Hardware, operating systems, file management, and basic software use. Entry point for computational engineering work.",
     "Use OS file system fluently. Understand CPU, RAM, and storage roles. Install and manage software."),
    ("f_spreadsheets", "Spreadsheet & Data Fundamentals", 0, "CS", 25, 8, "middle",
     "Excel/Google Sheets for engineering calculations, charting, and basic data analysis. Used in every engineering discipline.",
     "Build engineering calculation sheets with functions, charts, and data tables. Use VLOOKUP and conditional formatting."),
    ("f_algebra2", "Algebra II", 0, "MATH", 70, 22, "hs",
     "Quadratic, polynomial, exponential, and logarithmic functions. Complex numbers. Sequences and series.",
     "Factor polynomials. Solve quadratics. Work with exponential/log functions. Understand complex number arithmetic."),
    ("f_trig", "Trigonometry", 0, "MATH", 45, 16, "hs",
     "Sine, cosine, tangent, unit circle, identities, inverse trig, and triangle solving. Essential for vectors, waves, and AC circuits.",
     "Evaluate all six trig functions. Prove identities. Solve triangles using law of sines/cosines."),
    ("f_precalc", "Precalculus", 0, "MATH", 80, 25, "hs",
     "Functions, transformations, polar coordinates, parametric equations, vectors, and limits. Bridges algebra to calculus.",
     "Analyze and transform functions. Work with vectors in 2D. Evaluate limits graphically and numerically."),
    ("f_calculus1", "Calculus I — Differentiation", 0, "MATH", 90, 26, "hs",
     "Limits, derivatives, differentiation rules, related rates, optimization, and curve sketching. The mathematical language of change — central to all engineering analysis.",
     "Differentiate all elementary functions using chain, product, and quotient rules. Solve optimization and related-rates problems."),
    ("f_calculus2", "Calculus II — Integration", 0, "MATH", 90, 26, "hs",
     "Definite and indefinite integrals, integration techniques, improper integrals, sequences, and series. Used in energy calculations, signal processing, and structural mechanics.",
     "Evaluate integrals using substitution, parts, and partial fractions. Test series for convergence."),
    ("f_physics_mech", "Physics — Mechanics", 0, "SCI", 65, 20, "hs",
     "Kinematics, Newton's laws, work/energy/power, momentum, rotation, and gravitation. The physical foundation for all mechanical and civil engineering.",
     "Apply Newton's laws to multi-body systems. Solve energy/momentum conservation problems. Analyze rotational dynamics."),
    ("f_physics_em", "Physics — Electricity & Magnetism", 0, "SCI", 60, 18, "hs",
     "Electric fields, Coulomb's law, circuits, capacitance, magnetic fields, Faraday's law, and Maxwell's equations. Prerequisite for all electrical engineering.",
     "Apply Kirchhoff's laws to DC circuits. Calculate forces and fields. Understand electromagnetic induction."),
    ("f_physics_waves", "Physics — Waves, Optics & Modern", 0, "SCI", 50, 14, "hs",
     "Wave motion, sound, optics, quantum basics, nuclear physics, and special relativity. Background for materials science, nuclear, and photonics engineering.",
     "Solve wave interference problems. Apply photoelectric effect. Understand atomic spectra and radioactive decay."),
    ("f_chem_general", "General Chemistry", 0, "SCI", 70, 20, "hs",
     "Atomic structure, bonding, stoichiometry, thermochemistry, equilibrium, acids/bases, and electrochemistry. Essential for chemical, materials, and environmental engineering.",
     "Balance redox reactions. Solve equilibrium and stoichiometry problems. Interpret phase diagrams."),
    ("f_bio_basic", "Biology — Cell & Molecular Basics", 0, "SCI", 40, 12, "hs",
     "Cell structure, metabolism, DNA replication, and basic genetics. Required for biomedical and environmental engineering.",
     "Describe cell cycle, ATP production, and DNA transcription/translation. Explain Mendelian inheritance."),
    ("f_tech_writing", "Technical Writing & Communication", 0, "ENG", 35, 10, "hs",
     "Reports, specifications, lab documentation, and engineering drawings interpretation. Critical for professional engineering practice.",
     "Write a clear technical report. Interpret engineering drawings and specifications. Present data effectively."),
    ("adv_multivariable", "Multivariable Calculus", 1, "MATH", 90, 24, None,
     "Partial derivatives, multiple integrals, vector calculus, Green's/Stokes'/Divergence theorems. Used in fluid mechanics, electromagnetics, and heat transfer.",
     "Compute gradient, divergence, curl. Evaluate double and triple integrals. Apply fundamental theorems of vector calculus."),
    ("adv_linear_alg", "Linear Algebra", 1, "MATH", 90, 25, None,
     "Matrices, determinants, eigenvalues/eigenvectors, vector spaces, and linear transformations. The language of structural analysis, FEA, ML, and control systems.",
     "Solve systems via row reduction. Find eigenvalues and eigenvectors. Apply SVD. Understand coordinate transformations."),
    ("adv_diff_eq", "Differential Equations", 1, "MATH", 100, 28, None,
     "ODEs, PDEs, Laplace transforms, and systems of equations. Models vibration, heat transfer, fluid flow, and circuit dynamics.",
     "Solve 1st and 2nd order ODEs analytically. Apply Laplace transforms. Solve simple PDEs by separation of variables."),
    ("adv_numerical", "Numerical Methods", 1, "MATH", 80, 20, None,
     "Root-finding, interpolation, numerical integration, solving ODEs/PDEs numerically, and matrix decomposition.",
     "Implement Newton-Raphson, Runge-Kutta, and finite difference methods. Assess numerical stability and error."),
    ("adv_complex_anal", "Complex Analysis", 1, "MATH", 75, 18, None,
     "Complex functions, contour integration, residues, conformal mapping, and Z-transforms. Used in signal processing, control theory, and fluid dynamics.",
     "Apply Cauchy's theorem. Evaluate integrals using residues. Understand conformal mappings."),
    ("adv_optimization", "Optimization & Linear Programming", 1, "MATH", 80, 20, None,
     "Constrained and unconstrained optimization, linear programming, simplex method, and gradient descent.",
     "Formulate and solve LP problems. Apply KKT conditions for constrained optimization. Implement gradient descent."),
    ("adv_stats_eng", "Engineering Statistics", 1, "MATH", 70, 18, None,
     "Regression, design of experiments (DOE), reliability statistics, statistical process control, and hypothesis testing applied to engineering data.",
     "Conduct DOE and ANOVA. Fit regression models. Calculate MTBF. Build control charts (X-bar, R)."),
    ("adv_discrete", "Discrete Mathematics", 1, "MATH", 75, 20, None,
     "Graph theory, combinatorics, number theory, and formal logic. Foundation for computer engineering, network design, and algorithm analysis.",
     "Analyze graph connectivity and spanning trees. Count using permutations/combinations. Prove statements by induction."),
    ("adv_prog_eng", "Programming for Engineers", 1, "CS", 70, 18, None,
     "Python and/or MATLAB for numerical computation, data processing, and simulation. Engineers use code to automate calculations and visualize results.",
     "Write Python/MATLAB scripts for numerical integration, data plotting, and solving systems of equations."),
    ("adv_matlab", "MATLAB & Simulink", 1, "CS", 60, 14, None,
     "MATLAB for matrix computation, signal processing, and control systems. Simulink for block-diagram simulation of dynamic systems.",
     "Implement control systems in Simulink. Use MATLAB for ODE solving, FFT, and data analysis."),
    ("adv_cpp", "C / C++ for Engineering", 1, "CS", 90, 22, None,
     "Low-level programming for embedded systems, real-time software, and performance-critical engineering applications.",
     "Manage memory manually. Implement data structures. Write interrupt service routines. Profile performance."),
    ("adv_cad", "CAD — 2D & 3D Design", 1, "ENG", 60, 14, None,
     "AutoCAD for 2D drafting and SolidWorks/Fusion 360 for 3D parametric modeling. All engineering disciplines use CAD to communicate designs.",
     "Produce fully dimensioned 2D drawings. Build parametric 3D assemblies. Generate engineering drawings from models."),
    ("adv_fea", "Finite Element Analysis", 1, "ENG", 85, 20, None,
     "FEA theory (weak form, shape functions, meshing), structural/thermal/CFD analysis using ANSYS or Abaqus.",
     "Build and mesh a 3D structural model. Set boundary conditions and loads. Interpret stress, deformation, and convergence results."),
    ("adv_cfd", "Computational Fluid Dynamics", 1, "ENG", 85, 20, None,
     "Navier-Stokes discretization, turbulence modeling (k-ε, k-ω, LES), meshing strategies, and OpenFOAM/ANSYS Fluent.",
     "Set up and run a RANS simulation. Select appropriate turbulence model. Post-process velocity/pressure fields."),
    ("adv_systems_model", "System Modeling & Simulation", 1, "ENG", 70, 16, None,
     "Bond graphs, block diagrams, state-space modeling, and multi-domain simulation (mechanical, electrical, hydraulic).",
     "Build state-space model from physical equations. Simulate in Simulink. Linearize nonlinear models."),
    ("me_statics", "Statics", 1, "ME", 70, 20, None,
     "Equilibrium of rigid bodies, free-body diagrams, trusses, frames, and friction. The starting point for structural and mechanical analysis.",
     "Draw complete FBDs. Solve 3D equilibrium problems. Analyze pin-jointed trusses by method of joints and sections."),
    ("me_dynamics", "Dynamics", 1, "ME", 75, 20, None,
     "Kinematics and kinetics of particles and rigid bodies, work-energy and impulse-momentum methods, and vibration introduction.",
     "Solve planar rigid-body kinematics. Apply work-energy theorem to mechanisms. Analyze projectile and circular motion."),
    ("me_mechanics_mats", "Mechanics of Materials", 1, "ME", 80, 22, None,
     "Stress, strain, Hooke's law, bending, shear, torsion, buckling, and failure criteria. Foundation for structural and component design.",
     "Draw shear-force and bending-moment diagrams. Calculate deflections. Apply von Mises and Tresca failure criteria."),
    ("me_thermo", "Thermodynamics", 1, "ME", 90, 24, None,
     "Laws of thermodynamics, thermodynamic properties, power cycles (Rankine, Brayton, Otto), refrigeration, and mixtures.",
     "Analyze Rankine and Brayton cycles for efficiency. Apply first and second laws to open and closed systems. Use steam tables."),
    ("me_fluid", "Fluid Mechanics", 1, "ME", 90, 24, None,
     "Fluid statics, continuity, Bernoulli, momentum, viscous flow, pipe systems, dimensional analysis, and turbomachinery introduction.",
     "Apply Bernoulli and momentum equations. Solve pipe flow problems using Moody chart. Perform dimensional analysis."),
    ("me_heat_transfer", "Heat Transfer", 1, "ME", 85, 22, None,
     "Conduction, convection, radiation, heat exchangers, and coupled thermal systems. Essential for thermal management in all engineering.",
     "Solve 1D conduction problems. Calculate convective heat transfer coefficients. Design simple heat exchangers."),
    ("me_machine_design", "Machine Design", 1, "ME", 80, 20, None,
     "Fatigue analysis, shaft design, bearings, gears, fasteners, springs, clutches, and tolerancing. Translates analysis into physical components.",
     "Apply Goodman diagram for fatigue. Size shafts and select bearings. Design gear trains for torque/speed requirements."),
    ("me_manufacturing", "Manufacturing Processes", 1, "ME", 70, 18, None,
     "Casting, forming, machining, welding, polymer processing, and additive manufacturing. How designed parts are actually made.",
     "Select appropriate manufacturing process for a given geometry/material/volume. Estimate cost and cycle time."),
    ("me_vibrations", "Mechanical Vibrations", 1, "ME", 80, 20, None,
     "Free and forced vibration, damping, resonance, multi-DOF systems, and modal analysis. Critical for rotating machinery and structural dynamics.",
     "Analyze SDOF and 2DOF free/forced vibration. Find natural frequencies and mode shapes. Design vibration isolators."),
    ("ee_circuits", "Circuit Analysis", 1, "EE", 80, 22, None,
     "Kirchhoff's laws, nodal/mesh analysis, superposition, Thévenin/Norton, capacitors, inductors, transient response, and AC analysis.",
     "Solve DC and AC circuits using KVL/KCL. Apply Thévenin theorem. Analyze RC/RL/RLC transient and frequency responses."),
    ("ee_electronics", "Electronics — Analog", 1, "EE", 85, 22, None,
     "Diodes, BJTs, MOSFETs, op-amps, amplifier design, feedback, and frequency response. Foundation for sensor interfaces and power electronics.",
     "Design BJT and MOSFET amplifiers. Analyze op-amp circuits. Determine gain, bandwidth, and stability."),
    ("ee_digital", "Digital Electronics & Logic Design", 1, "EE", 80, 22, None,
     "Boolean algebra, combinational/sequential logic, state machines, HDL (VHDL/Verilog), and FPGA/ASIC basics.",
     "Design and minimize combinational circuits. Implement FSMs. Write basic VHDL/Verilog. Program an FPGA."),
    ("ee_signals", "Signals & Systems", 1, "EE", 85, 22, None,
     "Linear time-invariant systems, convolution, Fourier/Laplace/Z transforms, frequency response, filtering, and sampling.",
     "Compute Fourier transforms analytically and via FFT. Design FIR/IIR filters. Analyze system frequency response using Bode plots."),
    ("ee_electromagnetics", "Electromagnetic Fields", 1, "EE", 90, 24, None,
     "Maxwell's equations, static and dynamic fields, transmission lines, waveguides, and antenna principles.",
     "Apply Maxwell's equations to boundary-value problems. Solve transmission-line problems. Compute radiation patterns."),
    ("ee_power", "Power Systems & Energy", 1, "EE", 80, 20, None,
     "AC power, transformers, three-phase systems, generators, motors, power flow, and grid operation.",
     "Solve three-phase power flow problems. Analyze transformer performance. Select motors for load requirements."),
    ("ee_control", "Control Systems", 1, "EE", 90, 24, None,
     "Open/closed-loop systems, transfer functions, root locus, Bode analysis, PID design, state-space representation, and stability.",
     "Design PID controllers. Assess stability via Routh-Hurwitz, root locus, and Nyquist. Design state-feedback controllers."),
    ("ee_microcontrollers", "Microcontrollers & Embedded Systems", 1, "EE", 85, 20, None,
     "Microcontroller architecture, GPIO, timers, ADC/DAC, UART/SPI/I2C, interrupt handling, and real-time operating systems.",
     "Program microcontroller peripherals in C. Interface sensors and actuators. Implement basic RTOS tasks."),
    ("ee_vlsi", "VLSI Design", 1, "EE", 90, 22, None,
     "CMOS circuit design, logic synthesis, place-and-route, timing analysis, and chip design flow.",
     "Design CMOS logic gates at transistor level. Perform static timing analysis. Complete a digital design through place-and-route."),
    ("ee_telecom", "Telecommunications & Wireless", 1, "EE", 80, 18, None,
     "Modulation, coding, channel capacity, wireless channels, 5G/LTE fundamentals, and communication system design.",
     "Compute channel capacity and link budget. Implement AM/FM/QAM modulation. Analyze BER for AWGN channels."),
    ("ce_surveying", "Surveying & Geomatics", 1, "CE", 55, 14, None,
     "Leveling, traversing, GPS, total station, photogrammetry, and GIS fundamentals.",
     "Perform differential leveling. Calculate traverse closure errors. Import GPS data into GIS software."),
    ("ce_structural", "Structural Analysis", 1, "CE", 85, 22, None,
     "Determinate and indeterminate structures, influence lines, virtual work, slope-deflection, moment distribution, and matrix methods.",
     "Analyze multi-span beams and frames. Draw influence lines. Apply slope-deflection method to portal frames."),
    ("ce_concrete", "Reinforced Concrete Design", 1, "CE", 80, 20, None,
     "ACI code, beam/slab/column/footing design, ductility, and serviceability.",
     "Design RC beams, columns, and one-way slabs to ACI 318. Check deflection and crack width serviceability limits."),
    ("ce_steel", "Steel Design", 1, "CE", 75, 18, None,
     "AISC LRFD/ASD for beams, columns, connections, and frames.",
     "Design W-section beams and columns. Size bolted and welded connections. Analyze braced and moment frames."),
    ("ce_geotech", "Geotechnical Engineering", 1, "CE", 80, 20, None,
     "Soil classification, compaction, permeability, consolidation, shear strength, bearing capacity, and slope stability.",
     "Classify soils. Calculate consolidation settlement. Determine bearing capacity for spread footings. Analyze slope stability."),
    ("ce_hydraulics", "Hydraulics & Hydrology", 1, "CE", 80, 20, None,
     "Open-channel flow, pipe networks, stormwater management, watershed analysis, flood routing, and groundwater.",
     "Analyze open-channel flow using Manning's equation. Design stormwater detention. Perform flood-frequency analysis."),
    ("ce_transport", "Transportation Engineering", 1, "CE", 70, 18, None,
     "Highway design, traffic flow, pavement design, intersection analysis, and transit planning.",
     "Design horizontal/vertical highway alignments. Perform intersection level-of-service analysis. Design flexible pavement."),
    ("ce_construction_mgmt", "Construction Management", 1, "CE", 65, 16, None,
     "Project scheduling (CPM/PERT), cost estimation, contracts, site safety, and project delivery methods.",
     "Build a CPM schedule and identify critical path. Prepare quantity takeoffs. Understand construction contract types."),
    ("ce_env_eng", "Environmental Engineering", 1, "CE", 75, 18, None,
     "Water treatment, wastewater treatment, air quality, solid waste management, and environmental impact assessment.",
     "Design a primary/secondary wastewater treatment train. Calculate pollutant dispersion. Perform EIA for a linear project."),
    ("che_mass_energy", "Material & Energy Balances", 1, "CHE", 80, 22, None,
     "Stoichiometry, mass and energy balances for reactive and non-reactive systems, recycle, and purge streams.",
     "Perform complete mass and energy balances for multi-unit processes with recycle. Solve degree-of-freedom analyses."),
    ("che_thermo", "Chemical Engineering Thermodynamics", 1, "CHE", 90, 24, None,
     "Phase equilibrium, equations of state, VLE, chemical equilibrium, activity coefficients, and energy analysis of chemical processes.",
     "Calculate VLE using Raoult's law and EOS models. Determine chemical equilibrium compositions. Compute reaction enthalpy."),
    ("che_transport", "Transport Phenomena", 1, "CHE", 95, 24, None,
     "Unified treatment of momentum, heat, and mass transfer — the theoretical backbone of chemical engineering design.",
     "Derive transport equations from first principles. Solve coupled heat and mass transfer problems. Apply analogies between transport modes."),
    ("che_kinetics", "Chemical Reaction Engineering", 1, "CHE", 90, 22, None,
     "Reaction kinetics, reactor design (CSTR, PFR, PBR), residence time distribution, and catalysis.",
     "Design CSTR and PFR for given conversions. Determine rate laws from experimental data. Analyze residence time distributions."),
    ("che_separations", "Separation Processes", 1, "CHE", 85, 22, None,
     "Distillation, absorption, extraction, adsorption, and membrane processes.",
     "Design distillation columns using McCabe-Thiele method. Select and size extraction equipment. Analyze membrane performance."),
    ("che_process_design", "Process Design & Economics", 1, "CHE", 85, 20, None,
     "Process flowsheet development, equipment sizing, economic analysis, and HAZOP studies.",
     "Develop a complete PFD and P&ID. Perform capital cost estimation. Conduct HAZOP on a process section."),
    ("che_process_control", "Process Control", 1, "CHE", 80, 20, None,
     "Feedback and feedforward control, PID tuning, cascade control, and process dynamics.",
     "Tune PID controllers using IMC and Ziegler-Nichols methods. Analyze loop stability. Design feedforward compensation."),
    ("che_polymer", "Polymer Science & Engineering", 1, "CHE", 75, 18, None,
     "Polymer synthesis, structure-property relationships, rheology, and polymer processing.",
     "Describe addition and condensation polymerization mechanisms. Calculate molecular weight distributions. Analyze polymer rheology."),
    ("aero_aero", "Aerodynamics", 1, "AERO", 90, 24, None,
     "Potential flow, boundary layers, lift and drag generation, airfoil theory, compressible flow, and supersonic aerodynamics.",
     "Apply thin airfoil theory. Calculate lift and drag coefficients. Analyze boundary-layer separation and transition."),
    ("aero_flight_mech", "Flight Mechanics & Performance", 1, "AERO", 80, 20, None,
     "Equations of motion, static and dynamic stability, range/endurance analysis, V-n diagrams, and aircraft performance.",
     "Calculate aircraft range and endurance. Analyze static longitudinal stability. Construct V-n diagrams."),
    ("aero_propulsion", "Aerospace Propulsion", 1, "AERO", 85, 22, None,
     "Jet engine thermodynamic cycles, rocket propulsion fundamentals, nozzle design, and turbomachinery.",
     "Analyze ideal turbojet and turbofan cycles. Calculate rocket specific impulse and thrust. Design converging-diverging nozzles."),
    ("aero_structures", "Aerospace Structures", 1, "AERO", 85, 22, None,
     "Thin-walled beams, buckling, fatigue in flight structures, composite laminates, and aeroelasticity basics.",
     "Analyze thin-walled open and closed sections. Apply buckling criteria. Perform laminate analysis using CLT."),
    ("aero_orbital", "Orbital Mechanics", 1, "AERO", 75, 18, None,
     "Kepler's laws, orbital elements, Hohmann transfers, perturbations, and launch windows.",
     "Calculate orbital parameters from state vectors. Determine Δv for Hohmann transfers. Plan interplanetary trajectories."),
    ("aero_avionics", "Avionics & Navigation Systems", 1, "AERO", 75, 18, None,
     "GPS/INS navigation, autopilot systems, flight management computers, and avionic bus architectures.",
     "Explain INS error propagation. Analyze GPS positioning accuracy. Describe MIL-STD-1553 bus operation."),
    ("bme_physiology", "Physiology for Engineers", 1, "BME", 80, 20, None,
     "Cardiovascular, respiratory, musculoskeletal, and neural systems from a quantitative engineering perspective.",
     "Model cardiac output using fluid mechanics analogies. Analyze ECG waveforms. Describe muscle mechanics quantitatively."),
    ("bme_biomechanics", "Biomechanics", 1, "BME", 80, 20, None,
     "Mechanics of biological tissues, gait analysis, joint mechanics, musculoskeletal modeling, and implant mechanics.",
     "Perform gait analysis. Calculate joint reaction forces. Characterize viscoelastic tissue behavior."),
    ("bme_bioinstrumentation", "Bioinstrumentation", 1, "BME", 75, 18, None,
     "Transducers, biosignal acquisition, filtering, biopotentials (ECG/EEG/EMG), and medical device design.",
     "Design biopotential amplifier circuits. Filter EMG and ECG signals. Apply ADC specifications to biosignal acquisition."),
    ("bme_biomaterials", "Biomaterials", 1, "BME", 75, 18, None,
     "Biocompatibility, metals/ceramics/polymers in implants, surface modification, degradation, and regulatory pathway basics.",
     "Evaluate biocompatibility per ISO 10993. Compare material properties for implant applications. Describe sterilization effects."),
    ("bme_medical_imaging", "Medical Imaging", 1, "BME", 80, 20, None,
     "X-ray, CT, MRI, ultrasound, nuclear medicine, and image reconstruction mathematics.",
     "Explain CT reconstruction using filtered back projection. Describe MRI pulse sequences. Analyze ultrasound beam characteristics."),
    ("bme_tissue_eng", "Tissue Engineering & Regenerative Medicine", 1, "BME", 80, 18, None,
     "Scaffolds, cell culture, bioreactors, growth factors, and organ-on-a-chip technologies.",
     "Design a scaffold for bone tissue engineering. Characterize cell viability and proliferation. Describe mass transport in bioreactors."),
    ("bme_reg_affairs", "Medical Device Regulation & FDA Pathway", 1, "BME", 55, 12, None,
     "510(k) and PMA pathways, ISO 13485, risk management per ISO 14971, and clinical trials basics.",
     "Classify a medical device per FDA regulations. Prepare a risk management plan. Outline 510(k) submission requirements."),
    ("enve_water", "Water & Wastewater Treatment", 1, "ENVE", 80, 20, None,
     "Physical, chemical, and biological treatment processes, unit operation design, effluent standards, and water reuse.",
     "Design clarifiers and biological treatment systems. Calculate disinfection byproduct formation. Meet effluent quality standards."),
    ("enve_air", "Air Quality Engineering", 1, "ENVE", 75, 18, None,
     "Air pollutants, atmospheric dispersion modeling, control technologies, and emission inventories.",
     "Apply Gaussian dispersion model. Select and design air pollution control equipment. Prepare emission inventory reports."),
    ("enve_solid_waste", "Solid & Hazardous Waste Management", 1, "ENVE", 65, 16, None,
     "Waste characterization, landfill design, remediation, RCRA/CERCLA regulations, and waste minimization strategies.",
     "Design a sanitary landfill. Develop a remediation plan for a contaminated site. Apply RCRA classification to waste streams."),
    ("enve_sustainability", "Sustainability & Life Cycle Assessment", 1, "ENVE", 65, 14, None,
     "LCA methodology, carbon footprinting, circular economy, renewable energy systems, and environmental impact metrics.",
     "Perform an ISO 14040-compliant LCA. Calculate Scope 1/2/3 emissions. Design a circular material flow system."),
    ("enve_hydrology", "Hydrology & Groundwater", 1, "ENVE", 75, 18, None,
     "Surface hydrology, groundwater flow, contaminant transport, aquifer characterization, and watershed management.",
     "Apply Darcy's law to groundwater flow. Perform rational method flood calculation. Model contaminant transport in aquifers."),
    ("ie_ergonomics", "Ergonomics & Human Factors", 1, "IE", 60, 14, None,
     "Anthropometry, workstation design, cognitive load, human error, and usability engineering.",
     "Evaluate workstation ergonomics using RULA/REBA. Conduct task analysis. Apply human error probability estimation."),
    ("ie_work_study", "Work Study & Time-Motion Analysis", 1, "IE", 55, 14, None,
     "Method study, time standards, MTM systems, and work measurement for productivity improvement.",
     "Conduct time study. Develop standard time with allowances. Apply predetermined time systems (MOST/MTM-1)."),
    ("ie_operations", "Operations Research", 1, "IE", 85, 22, None,
     "Linear programming, integer programming, dynamic programming, queuing theory, simulation, and decision analysis.",
     "Formulate and solve LP/IP models. Analyze queuing systems. Build and run discrete-event simulations."),
    ("ie_quality", "Quality Engineering", 1, "IE", 70, 18, None,
     "SPC, measurement systems analysis, Six Sigma (DMAIC), DOE, reliability engineering, and quality management systems.",
     "Conduct MSA studies. Build control charts. Execute a DMAIC project. Perform Weibull reliability analysis."),
    ("ie_supply_chain", "Supply Chain & Logistics", 1, "IE", 70, 18, None,
     "Inventory models, facility location, network optimization, demand forecasting, and lean/JIT manufacturing.",
     "Apply EOQ and safety stock models. Solve facility location LP. Forecast demand using exponential smoothing."),
    ("ie_facilities", "Facilities Planning & Layout", 1, "IE", 60, 14, None,
     "Plant layout methodologies, material handling equipment selection, and lean facility design.",
     "Develop a systematic layout using SLP methodology. Select and justify material handling equipment. Apply value stream mapping."),
    ("ie_systems_eng", "Systems Engineering", 1, "IE", 75, 18, None,
     "Requirements engineering, architecture modeling (SysML), FMEA, integration and test, and MBSE.",
     "Develop a system requirements specification. Create SysML block and activity diagrams. Conduct FMEA with RPN scoring."),
    ("ie_project_mgmt", "Project Management", 1, "IE", 60, 14, None,
     "CPM/PERT scheduling, cost/schedule performance, risk management, Agile/waterfall methods, and PMI framework.",
     "Build a WBS and CPM network. Calculate EVM metrics (CPI/SPI). Prepare a project risk register."),
    ("mat_structure", "Structure of Materials", 1, "MAT", 75, 20, None,
     "Crystal structures, defects, diffusion, phase diagrams, and microstructure.",
     "Interpret phase diagrams. Calculate diffusion distances. Identify crystal structures from XRD patterns."),
    ("mat_mechanical", "Mechanical Behavior of Materials", 1, "MAT", 80, 20, None,
     "Elastic/plastic deformation, fracture mechanics, fatigue, creep, and strengthening mechanisms.",
     "Apply fracture mechanics (K_IC). Perform fatigue life calculation. Predict creep rupture life."),
    ("mat_processing", "Materials Processing", 1, "MAT", 70, 18, None,
     "Heat treatment, forming, casting, welding metallurgy, thin film deposition, and powder processing.",
     "Design a heat treatment cycle for steel. Predict weld zone microstructure. Describe PVD/CVD thin film processes."),
    ("mat_electronic", "Electronic & Optical Materials", 1, "MAT", 80, 20, None,
     "Semiconductors, dielectrics, magnetic materials, photovoltaics, and superconductors.",
     "Calculate band gap and carrier concentration. Analyze p-n junction under bias. Describe solar cell operation."),
    ("mat_characterization", "Materials Characterization", 1, "MAT", 65, 16, None,
     "XRD, SEM/TEM, EDS, AFM, mechanical testing, and thermal analysis (DSC, TGA).",
     "Interpret SEM and XRD data. Perform and analyze tensile and hardness tests. Use DSC for phase transition analysis."),
    ("mat_biomaterials", "Biomaterials & Nanomaterials", 1, "MAT", 70, 16, None,
     "Biocompatibility, scaffold materials, nanomaterial synthesis, quantum dots, and carbon nanostructures.",
     "Compare metals, ceramics, and polymers for implant use. Synthesize and characterize nanoparticles. Describe nanoscale effects."),
    ("nuke_physics", "Nuclear Physics & Reactions", 1, "NUKE", 85, 22, None,
     "Nuclear structure, radioactive decay, nuclear reactions, cross sections, fission, and fusion.",
     "Calculate decay chains and activities. Determine Q-values for reactions. Interpret neutron cross-section data."),
    ("nuke_transport", "Radiation Transport & Shielding", 1, "NUKE", 85, 22, None,
     "Neutron and photon transport, Boltzmann equation, Monte Carlo methods, and shielding design.",
     "Apply neutron diffusion theory. Design gamma shielding. Use Monte Carlo code (MCNP/OpenMC) for a shielding problem."),
    ("nuke_reactor", "Nuclear Reactor Theory", 1, "NUKE", 90, 24, None,
     "Criticality, reactivity coefficients, reactor kinetics, neutron moderation, fuel management, and reactor types.",
     "Solve criticality problem using four-factor formula. Analyze point kinetics. Compare PWR, BWR, and fast reactor designs."),
    ("nuke_thermal", "Nuclear Thermal-Hydraulics", 1, "NUKE", 80, 20, None,
     "Heat generation in fuel, coolant flow, CHF, decay heat, and safety system analysis.",
     "Calculate fuel pin temperature distribution. Determine DNB margin. Analyze loss-of-coolant accident sequence."),
    ("nuke_safety", "Nuclear Safety & Regulation", 1, "NUKE", 70, 16, None,
     "Defense-in-depth, probabilistic risk assessment (PRA), NRC regulations, and emergency planning.",
     "Build a simple fault tree and event tree. Interpret PRA results. Apply NRC 10 CFR requirements to a design scenario."),
    ("rob_kinematics", "Robot Kinematics", 1, "ROB", 80, 20, None,
     "Forward/inverse kinematics, DH parameters, Jacobians, and workspace analysis for serial and parallel manipulators.",
     "Derive FK/IK for 6-DOF robot using DH convention. Compute Jacobian. Analyze workspace and singularities."),
    ("rob_dynamics_ctrl", "Robot Dynamics & Control", 1, "ROB", 85, 22, None,
     "Lagrangian dynamics, computed-torque control, PD/PID joint control, force control, and impedance control.",
     "Derive equations of motion for a 3-DOF arm. Design computed-torque controller. Implement impedance control."),
    ("rob_perception", "Robot Perception & Computer Vision", 1, "ROB", 85, 20, None,
     "Camera models, image processing, feature detection, stereo vision, point clouds, SLAM, and deep learning for perception.",
     "Calibrate a camera. Implement stereo depth estimation. Run SLAM on a mobile robot. Deploy a detection network."),
    ("rob_planning", "Motion Planning", 1, "ROB", 75, 18, None,
     "Configuration space, sampling-based planners (RRT, PRM), potential fields, trajectory optimization, and task planning.",
     "Implement RRT for a 2D environment. Generate smooth trajectories. Plan multi-step pick-and-place tasks."),
    ("rob_actuators", "Actuators, Sensors & Mechanisms", 1, "ROB", 70, 16, None,
     "DC/stepper/servo motors, encoders, IMUs, force/torque sensors, drive electronics, and mechanism design.",
     "Size actuators for a given load. Interface encoders and IMUs. Design a compliant mechanism."),
    ("rob_ros", "ROS & Robot Software", 1, "ROB", 70, 14, None,
     "ROS2 architecture, nodes/topics/services/actions, simulation with Gazebo, and robot software integration.",
     "Build a ROS2 workspace with custom nodes. Simulate a robot in Gazebo. Integrate perception, planning, and control stacks."),
    ("sp_mech_eng", "Mechanical Engineering", 2, "ME", None, 0, None,
     "Design and analysis of physical systems — machines, thermal systems, and structures. Broadest engineering discipline.",
     "Complete FE Exam-level competency across thermodynamics, mechanics, materials, and machine design."),
    ("sp_elec_eng", "Electrical Engineering", 2, "EE", None, 0, None,
     "Systems that generate, transmit, process, and use electrical energy and information.",
     "Complete FE Exam-level competency across circuits, signals, electromagnetics, power, and controls."),
    ("sp_comp_eng", "Computer Engineering", 2, "EE", None, 0, None,
     "Hardware-software co-design, digital systems, embedded systems, and processor architecture.",
     "Design digital systems from spec through HDL implementation. Interface hardware with embedded software."),
    ("sp_civil_eng", "Civil Engineering", 2, "CE", None, 0, None,
     "Design and construction of infrastructure — buildings, bridges, roads, water systems, and environmental systems.",
     "Complete FE Exam-level competency across structural analysis, geotechnical, hydraulics, and transportation."),
    ("sp_structural_eng", "Structural Engineering", 2, "CE", None, 0, None,
     "Advanced structural analysis and design for buildings, bridges, and infrastructure. Typically a post-graduate specialization.",
     "Design complex structural systems in steel and concrete. Perform seismic analysis. Meet professional engineering standards."),
    ("sp_chem_eng", "Chemical Engineering", 2, "CHE", None, 0, None,
     "Design and operation of processes that transform raw materials into useful products.",
     "Design a complete chemical process from reaction chemistry through separations, control, and economics."),
    ("sp_aero_eng", "Aerospace Engineering", 2, "AERO", None, 0, None,
     "Design of aircraft and spacecraft — aerodynamics, structures, propulsion, flight mechanics, and avionics.",
     "Perform conceptual design of an aircraft or spacecraft mission. Integrate all subsystems."),
    ("sp_bio_eng", "Biomedical Engineering", 2, "BME", None, 0, None,
     "Application of engineering principles to medicine and biology — medical devices, imaging, prosthetics, and tissue engineering.",
     "Design a medical device through concept, prototyping, and regulatory pathway. Characterize biological performance."),
    ("sp_env_eng", "Environmental Engineering", 2, "ENVE", None, 0, None,
     "Protection of the environment and public health through water/air/waste treatment, remediation, and sustainable design.",
     "Design integrated water and air treatment systems. Perform comprehensive environmental impact assessment."),
    ("sp_industrial_eng", "Industrial & Systems Engineering", 2, "IE", None, 0, None,
     "Optimization of complex systems of people, machines, materials, and energy for maximum efficiency and quality.",
     "Analyze and redesign a production system using lean, simulation, and OR tools. Demonstrate measurable improvement."),
    ("sp_materials_sci", "Materials Science & Engineering", 2, "MAT", None, 0, None,
     "Design and development of materials with tailored properties — metals, ceramics, polymers, composites, and nanomaterials.",
     "Select and specify materials for engineering applications. Design processing routes to achieve target microstructures."),
    ("sp_nuclear_eng", "Nuclear Engineering", 2, "NUKE", None, 0, None,
     "Design and operation of nuclear reactors and radiation systems for power generation, medicine, and research.",
     "Design a reactor core configuration. Perform safety analysis. Specify radiation protection measures."),
    ("sp_robotics_eng", "Robotics & Mechatronics", 2, "ROB", None, 0, None,
     "Integration of mechanical, electrical, and computational systems to build autonomous and intelligent machines.",
     "Build a complete robotic system from hardware through software — kinematics, sensing, planning, and control."),
    ("sp_mfg_eng", "Manufacturing Engineering", 2, "ME", None, 0, None,
     "Design of manufacturing systems and processes — from factory layout to CNC programming to quality systems.",
     "Design an end-to-end production process with documented quality system. Achieve target OEE."),
    ("sp_petroleum_eng", "Petroleum Engineering", 2, "CHE", None, 0, None,
     "Exploration, drilling, production, and reservoir engineering for oil and gas. Increasingly applied to geothermal and carbon capture.",
     "Perform reservoir simulation. Design drilling program. Optimize production through artificial lift."),
    ("hub_bs_eng", "Bachelor of Science in Engineering", 3, "CRED", None, 0, None,
     "4-year ABET-accredited engineering degree. Minimum credential for most professional engineering roles. Gateway to PE licensure.",
     "Pass FE Exam. Complete senior capstone design project. Meet ABET learning outcomes."),
    ("hub_ms_eng", "Master of Science in Engineering", 3, "CRED", None, 0, None,
     "Advanced specialization degree. Required for research roles, faculty positions, and specialized technical leadership.",
     "Complete thesis or project demonstrating independent research capability in chosen specialty."),
    ("hub_phd_eng", "PhD in Engineering", 3, "CRED", None, 0, None,
     "Research doctorate. Required for tenure-track faculty, national lab research, and advanced R&D leadership.",
     "Original research contribution to the field. Dissertation defense. Publication record."),
    ("hub_pe_license", "Professional Engineer (PE) License", 3, "CRED", None, 0, None,
     "State licensure required to offer engineering services to the public, stamp drawings, and lead engineering projects in regulated industries.",
     "Pass PE Exam. Accumulate 4 years of progressive engineering experience. Three professional references."),
    ("hub_cert_eng", "Professional Engineering Certification", 3, "CRED", None, 0, None,
     "Industry-specific certifications: PMP, Six Sigma Black Belt, AWS Certified Welding Inspector, Certified Energy Manager, etc.",
     "Pass relevant certification exam. Meet experience requirements. Maintain continuing education."),
    ("car_mech_eng", "Mechanical Engineer", 4, "ME", None, 0, None,
     "Designs, analyzes, and develops mechanical systems across automotive, aerospace, consumer products, and industrial sectors.",
     None),
    ("car_thermal_eng", "Thermal / HVAC Engineer", 4, "ME", None, 0, None,
     "Designs heating, ventilation, air conditioning, and thermal management systems for buildings, data centers, and vehicles.",
     None),
    ("car_mfg_eng", "Manufacturing Engineer", 4, "ME", None, 0, None,
     "Designs and optimizes manufacturing processes, tooling, and production systems for efficiency and quality.",
     None),
    ("car_automotive_eng", "Automotive Engineer", 4, "ME", None, 0, None,
     "Develops vehicle systems — powertrain, chassis, body, NVH, and safety — for passenger and commercial vehicles.",
     None),
    ("car_product_dev", "Product Development Engineer", 4, "ME", None, 0, None,
     "Leads design and development of new physical products from concept through manufacturing release.",
     None),
    ("car_elec_eng", "Electrical Engineer", 4, "EE", None, 0, None,
     "Designs electrical systems, circuits, and power infrastructure across energy, industrial, and consumer electronics sectors.",
     None),
    ("car_power_eng", "Power Systems Engineer", 4, "EE", None, 0, None,
     "Designs and operates electric power generation, transmission, and distribution systems including renewable energy integration.",
     None),
    ("car_controls_eng", "Controls / Automation Engineer", 4, "EE", None, 0, None,
     "Designs feedback control systems, PLC/SCADA systems, and automation solutions for industrial and robotics applications.",
     None),
    ("car_rf_eng", "RF / Antenna Engineer", 4, "EE", None, 0, None,
     "Designs radio frequency circuits, antennas, and wireless communication systems for telecom, radar, and satellites.",
     None),
    ("car_ic_designer", "IC / Chip Designer", 4, "EE", None, 0, None,
     "Designs analog or digital integrated circuits for processors, ASICs, and custom silicon.",
     None),
    ("car_embedded_eng", "Embedded Software / Firmware Engineer", 4, "EE", None, 0, None,
     "Develops low-level software running on microcontrollers and processors for automotive, IoT, medical devices, and aerospace.",
     None),
    ("car_avionics_eng", "Avionics / Systems Engineer", 4, "EE", None, 0, None,
     "Develops and integrates aircraft and spacecraft electronic systems — navigation, communication, and flight control.",
     None),
    ("car_civil_eng", "Civil Engineer", 4, "CE", None, 0, None,
     "Plans, designs, and oversees construction of infrastructure — buildings, bridges, roads, dams, and utilities.",
     None),
    ("car_struct_eng", "Structural Engineer", 4, "CE", None, 0, None,
     "Analyzes and designs load-bearing systems for buildings, bridges, and infrastructure to resist gravity, wind, and seismic forces.",
     None),
    ("car_geotechnical", "Geotechnical Engineer", 4, "CE", None, 0, None,
     "Evaluates subsurface conditions for foundations, tunnels, dams, and earthworks. Manages ground risk on construction projects.",
     None),
    ("car_transport_eng", "Transportation Engineer", 4, "CE", None, 0, None,
     "Plans and designs road, rail, and transit systems. Performs traffic analysis and intersection design.",
     None),
    ("car_water_resources", "Water Resources Engineer", 4, "CE", None, 0, None,
     "Designs water supply, flood control, irrigation, and stormwater management systems.",
     None),
    ("car_chem_eng", "Chemical Engineer", 4, "CHE", None, 0, None,
     "Designs and optimizes chemical processes for petrochemicals, pharmaceuticals, food, and specialty chemicals.",
     None),
    ("car_process_eng", "Process Engineer", 4, "CHE", None, 0, None,
     "Operates, optimizes, and troubleshoots chemical manufacturing processes.",
     None),
    ("car_process_safety", "Process Safety Engineer", 4, "CHE", None, 0, None,
     "Identifies and mitigates hazards in chemical plants through HAZOP, PHA, and PSM compliance.",
     None),
    ("car_pharma_mfg", "Pharmaceutical Manufacturing Engineer", 4, "CHE", None, 0, None,
     "Scales up and validates drug manufacturing processes under GMP regulations.",
     None),
    ("car_petroleum_eng", "Petroleum Engineer", 4, "CHE", None, 0, None,
     "Develops methods for extracting oil and gas. Covers reservoir engineering, drilling, and production optimization.",
     None),
    ("car_aero_eng", "Aerospace Engineer", 4, "AERO", None, 0, None,
     "Designs aircraft, spacecraft, and propulsion systems. Works across commercial aviation, defense, and space sectors.",
     None),
    ("car_propulsion_eng", "Propulsion Engineer", 4, "AERO", None, 0, None,
     "Designs and tests jet engines, rocket motors, and propulsion systems for aircraft and launch vehicles.",
     None),
    ("car_flight_test", "Flight Test Engineer", 4, "AERO", None, 0, None,
     "Plans and executes flight test campaigns to validate aircraft performance, handling qualities, and systems.",
     None),
    ("car_spacecraft_eng", "Spacecraft Systems Engineer", 4, "AERO", None, 0, None,
     "Integrates spacecraft subsystems — power, thermal, comms, propulsion, and attitude control — into a coherent system.",
     None),
    ("car_guidance_nav", "Guidance, Navigation & Control Engineer", 4, "AERO", None, 0, None,
     "Designs guidance algorithms, navigation filters, and flight control laws for aircraft, missiles, and spacecraft.",
     None),
    ("car_bme_eng", "Biomedical Engineer", 4, "BME", None, 0, None,
     "Develops medical devices and diagnostic equipment at the intersection of engineering and clinical medicine.",
     None),
    ("car_medical_device", "Medical Device Design Engineer", 4, "BME", None, 0, None,
     "Leads design control, verification/validation, and regulatory submission for implants, diagnostics, and surgical tools.",
     None),
    ("car_clinical_eng", "Clinical Engineer", 4, "BME", None, 0, None,
     "Manages and maintains medical technology in hospitals. Advises on equipment procurement and safety.",
     None),
    ("car_imaging_scientist", "Medical Imaging Scientist", 4, "BME", None, 0, None,
     "Develops and optimizes MRI, CT, and ultrasound systems and image reconstruction algorithms.",
     None),
    ("car_tissue_eng", "Tissue Engineer / Regenerative Medicine Scientist", 4, "BME", None, 0, None,
     "Develops cell-based therapies, organoids, and engineered tissues for drug testing and transplantation.",
     None),
    ("car_env_eng", "Environmental Engineer", 4, "ENVE", None, 0, None,
     "Designs solutions for water treatment, air quality, and site remediation. Works in consulting, government, and industry.",
     None),
    ("car_sustainability", "Sustainability Engineer", 4, "ENVE", None, 0, None,
     "Drives decarbonization and circular economy strategies for industrial companies and infrastructure projects.",
     None),
    ("car_remediation", "Environmental Remediation Specialist", 4, "ENVE", None, 0, None,
     "Designs and executes cleanup of contaminated soil and groundwater at Superfund and brownfield sites.",
     None),
    ("car_water_eng", "Water Treatment Engineer", 4, "ENVE", None, 0, None,
     "Designs and operates municipal water and wastewater treatment plants.",
     None),
    ("car_industrial_eng", "Industrial Engineer", 4, "IE", None, 0, None,
     "Optimizes production systems, supply chains, and business processes for efficiency, quality, and cost.",
     None),
    ("car_process_imp", "Process Improvement / Lean Engineer", 4, "IE", None, 0, None,
     "Drives lean manufacturing, Six Sigma, and Kaizen initiatives to eliminate waste and improve throughput.",
     None),
    ("car_supply_chain_eng", "Supply Chain Engineer", 4, "IE", None, 0, None,
     "Designs and optimizes supply networks, logistics, and inventory systems for global manufacturing.",
     None),
    ("car_quality_eng", "Quality Engineer", 4, "IE", None, 0, None,
     "Develops and maintains quality management systems, statistical process control, and product testing protocols.",
     None),
    ("car_systems_eng", "Systems Engineer", 4, "IE", None, 0, None,
     "Architects and integrates complex engineered systems across aerospace, defense, automotive, and tech sectors.",
     None),
    ("car_project_eng", "Engineering Project Manager", 4, "IE", None, 0, None,
     "Leads engineering projects from initiation through delivery — managing scope, schedule, cost, and risk.",
     None),
    ("car_materials_eng", "Materials Engineer", 4, "MAT", None, 0, None,
     "Selects, tests, and develops materials for products and processes across aerospace, automotive, electronics, and biomedical sectors.",
     None),
    ("car_metallurgist", "Metallurgist", 4, "MAT", None, 0, None,
     "Specializes in metal alloys — composition, processing, microstructure, and performance for structural and functional applications.",
     None),
    ("car_composites_eng", "Composites Engineer", 4, "MAT", None, 0, None,
     "Designs carbon fiber, glass fiber, and polymer matrix composites for aerospace, automotive, and sporting applications.",
     None),
    ("car_semiconductor", "Semiconductor Process Engineer", 4, "MAT", None, 0, None,
     "Develops and controls semiconductor fabrication processes (lithography, etch, deposition) in wafer fab environments.",
     None),
    ("car_nuclear_eng", "Nuclear Engineer", 4, "NUKE", None, 0, None,
     "Designs and operates nuclear reactors for power generation, naval propulsion, and research.",
     None),
    ("car_radiation_safety", "Radiation Protection / Health Physicist", 4, "NUKE", None, 0, None,
     "Ensures safe use of radiation sources in power plants, hospitals, and research facilities.",
     None),
    ("car_fusion_eng", "Fusion Engineer", 4, "NUKE", None, 0, None,
     "Develops plasma physics, magnet systems, and fusion reactor technology for commercial fusion.",
     None),
    ("car_robotics_eng", "Robotics Engineer", 4, "ROB", None, 0, None,
     "Designs robotic systems — hardware, kinematics, software, and integration — for manufacturing, logistics, and service robots.",
     None),
    ("car_autonomy_eng", "Autonomous Systems Engineer", 4, "ROB", None, 0, None,
     "Develops self-driving vehicles, drones, and autonomous mobile robots — perception, planning, and control.",
     None),
    ("car_mechatronics", "Mechatronics Engineer", 4, "ROB", None, 0, None,
     "Integrates mechanical, electrical, and software systems into intelligent machines and products.",
     None),
    ("car_research_eng", "Research Engineer / Scientist", 4, "ENG", None, 0, None,
     "Conducts applied R&D in industry or government labs — pushing the engineering frontier in specialized domains.",
     None),
    ("car_professor", "Engineering Professor", 4, "ENG", None, 0, None,
     "Teaches and leads research programs at universities. Trains the next generation of engineers.",
     None),
    ("car_tech_consultant", "Engineering Consultant", 4, "ENG", None, 0, None,
     "Provides expert technical advice and problem-solving to industry clients across multiple sectors.",
     None),
]

EDGES = [
    ("f_counting", "f_addition"),
    ("f_counting", "f_subtraction"),
    ("f_addition", "f_multiplication"),
    ("f_subtraction", "f_multiplication"),
    ("f_multiplication", "f_division"),
    ("f_division", "f_fractions"),
    ("f_fractions", "f_negative"),
    ("f_fractions", "f_ratios"),
    ("f_fractions", "f_percentages"),
    ("f_negative", "f_algebra1"),
    ("f_ratios", "f_algebra1"),
    ("f_percentages", "f_algebra1"),
    ("f_algebra1", "f_algebra2"),
    ("f_algebra1", "f_geometry"),
    ("f_algebra2", "f_trig"),
    ("f_geometry", "f_trig"),
    ("f_trig", "f_precalc"),
    ("f_algebra2", "f_precalc"),
    ("f_precalc", "f_calculus1"),
    ("f_calculus1", "f_calculus2"),
    ("f_algebra1", "f_stats_basic"),
    ("f_algebra2", "f_stats_basic"),
    ("f_algebra1", "f_logic"),
    ("f_comp_basics", "f_spreadsheets"),
    ("f_algebra1", "f_physics_mech"),
    ("f_calculus1", "f_physics_mech"),
    ("f_algebra2", "f_physics_em"),
    ("f_calculus1", "f_physics_em"),
    ("f_physics_mech", "f_physics_waves"),
    ("f_physics_em", "f_physics_waves"),
    ("f_algebra1", "f_chem_general"),
    ("f_fractions", "f_chem_general"),
    ("f_chem_general", "f_bio_basic"),
    ("f_physics_mech", "f_sci_method"),
    ("f_calculus1", "adv_multivariable"),
    ("f_calculus2", "adv_multivariable"),
    ("f_algebra2", "adv_linear_alg"),
    ("f_calculus1", "adv_linear_alg"),
    ("f_calculus2", "adv_diff_eq"),
    ("adv_linear_alg", "adv_diff_eq"),
    ("adv_linear_alg", "adv_numerical"),
    ("adv_diff_eq", "adv_numerical"),
    ("f_calculus2", "adv_complex_anal"),
    ("adv_diff_eq", "adv_complex_anal"),
    ("adv_linear_alg", "adv_optimization"),
    ("f_calculus1", "adv_optimization"),
    ("f_stats_basic", "adv_stats_eng"),
    ("adv_linear_alg", "adv_stats_eng"),
    ("f_algebra2", "adv_discrete"),
    ("f_logic", "adv_discrete"),
    ("f_comp_basics", "adv_prog_eng"),
    ("f_algebra1", "adv_prog_eng"),
    ("adv_prog_eng", "adv_matlab"),
    ("adv_prog_eng", "adv_cpp"),
    ("f_tech_writing", "adv_cad"),
    ("f_geometry", "adv_cad"),
    ("f_physics_mech", "me_statics"),
    ("f_calculus1", "me_statics"),
    ("me_statics", "me_dynamics"),
    ("f_calculus1", "me_dynamics"),
    ("me_statics", "me_mechanics_mats"),
    ("me_dynamics", "me_mechanics_mats"),
    ("f_calculus1", "me_thermo"),
    ("f_physics_mech", "me_thermo"),
    ("f_chem_general", "me_thermo"),
    ("me_thermo", "me_fluid"),
    ("adv_multivariable", "me_fluid"),
    ("f_physics_mech", "me_fluid"),
    ("me_thermo", "me_heat_transfer"),
    ("me_fluid", "me_heat_transfer"),
    ("adv_diff_eq", "me_heat_transfer"),
    ("me_mechanics_mats", "me_machine_design"),
    ("adv_stats_eng", "me_machine_design"),
    ("me_mechanics_mats", "me_manufacturing"),
    ("adv_cad", "me_manufacturing"),
    ("me_dynamics", "me_vibrations"),
    ("adv_diff_eq", "me_vibrations"),
    ("adv_linear_alg", "me_vibrations"),
    ("f_physics_em", "ee_circuits"),
    ("f_calculus1", "ee_circuits"),
    ("f_algebra2", "ee_circuits"),
    ("ee_circuits", "ee_electronics"),
    ("f_physics_em", "ee_electronics"),
    ("ee_circuits", "ee_digital"),
    ("f_logic", "ee_digital"),
    ("adv_discrete", "ee_digital"),
    ("ee_circuits", "ee_signals"),
    ("f_calculus2", "ee_signals"),
    ("adv_complex_anal", "ee_signals"),
    ("f_physics_em", "ee_electromagnetics"),
    ("adv_multivariable", "ee_electromagnetics"),
    ("adv_diff_eq", "ee_electromagnetics"),
    ("ee_circuits", "ee_power"),
    ("f_physics_em", "ee_power"),
    ("ee_signals", "ee_control"),
    ("adv_diff_eq", "ee_control"),
    ("adv_linear_alg", "ee_control"),
    ("ee_electronics", "ee_microcontrollers"),
    ("ee_digital", "ee_microcontrollers"),
    ("adv_cpp", "ee_microcontrollers"),
    ("ee_digital", "ee_vlsi"),
    ("adv_linear_alg", "ee_vlsi"),
    ("ee_signals", "ee_telecom"),
    ("ee_electromagnetics", "ee_telecom"),
    ("f_calculus1", "ce_surveying"),
    ("f_geometry", "ce_surveying"),
    ("me_statics", "ce_structural"),
    ("me_mechanics_mats", "ce_structural"),
    ("adv_linear_alg", "ce_structural"),
    ("ce_structural", "ce_concrete"),
    ("me_mechanics_mats", "ce_concrete"),
    ("ce_structural", "ce_steel"),
    ("me_mechanics_mats", "ce_steel"),
    ("f_physics_mech", "ce_geotech"),
    ("f_chem_general", "ce_geotech"),
    ("adv_stats_eng", "ce_geotech"),
    ("me_fluid", "ce_hydraulics"),
    ("adv_stats_eng", "ce_hydraulics"),
    ("f_stats_basic", "ce_transport"),
    ("ce_surveying", "ce_transport"),
    ("f_tech_writing", "ce_construction_mgmt"),
    ("adv_stats_eng", "ce_construction_mgmt"),
    ("f_chem_general", "ce_env_eng"),
    ("me_fluid", "ce_env_eng"),
    ("f_bio_basic", "ce_env_eng"),
    ("f_chem_general", "che_mass_energy"),
    ("f_calculus1", "che_mass_energy"),
    ("f_physics_mech", "che_mass_energy"),
    ("che_mass_energy", "che_thermo"),
    ("me_thermo", "che_thermo"),
    ("f_chem_general", "che_thermo"),
    ("che_thermo", "che_transport"),
    ("me_fluid", "che_transport"),
    ("adv_diff_eq", "che_transport"),
    ("me_heat_transfer", "che_transport"),
    ("f_chem_general", "che_kinetics"),
    ("che_thermo", "che_kinetics"),
    ("adv_diff_eq", "che_kinetics"),
    ("che_thermo", "che_separations"),
    ("che_mass_energy", "che_separations"),
    ("che_kinetics", "che_process_design"),
    ("che_separations", "che_process_design"),
    ("adv_stats_eng", "che_process_design"),
    ("adv_diff_eq", "che_process_control"),
    ("ee_control", "che_process_control"),
    ("che_process_design", "che_process_control"),
    ("f_chem_general", "che_polymer"),
    ("che_thermo", "che_polymer"),
    ("me_fluid", "aero_aero"),
    ("adv_multivariable", "aero_aero"),
    ("f_physics_mech", "aero_aero"),
    ("aero_aero", "aero_flight_mech"),
    ("me_dynamics", "aero_flight_mech"),
    ("adv_diff_eq", "aero_flight_mech"),
    ("me_thermo", "aero_propulsion"),
    ("me_fluid", "aero_propulsion"),
    ("aero_aero", "aero_propulsion"),
    ("me_mechanics_mats", "aero_structures"),
    ("adv_linear_alg", "aero_structures"),
    ("me_vibrations", "aero_structures"),
    ("f_physics_mech", "aero_orbital"),
    ("adv_diff_eq", "aero_orbital"),
    ("f_calculus2", "aero_orbital"),
    ("ee_control", "aero_avionics"),
    ("ee_microcontrollers", "aero_avionics"),
    ("aero_flight_mech", "aero_avionics"),
    ("f_bio_basic", "bme_physiology"),
    ("f_chem_general", "bme_physiology"),
    ("f_physics_mech", "bme_physiology"),
    ("bme_physiology", "bme_biomechanics"),
    ("me_statics", "bme_biomechanics"),
    ("me_mechanics_mats", "bme_biomechanics"),
    ("ee_circuits", "bme_bioinstrumentation"),
    ("ee_signals", "bme_bioinstrumentation"),
    ("bme_physiology", "bme_bioinstrumentation"),
    ("f_chem_general", "bme_biomaterials"),
    ("me_mechanics_mats", "bme_biomaterials"),
    ("f_bio_basic", "bme_biomaterials"),
    ("ee_signals", "bme_medical_imaging"),
    ("adv_linear_alg", "bme_medical_imaging"),
    ("f_physics_waves", "bme_medical_imaging"),
    ("f_bio_basic", "bme_tissue_eng"),
    ("bme_biomaterials", "bme_tissue_eng"),
    ("f_tech_writing", "bme_reg_affairs"),
    ("adv_stats_eng", "bme_reg_affairs"),
    ("f_chem_general", "enve_water"),
    ("me_fluid", "enve_water"),
    ("f_bio_basic", "enve_water"),
    ("f_chem_general", "enve_air"),
    ("adv_stats_eng", "enve_air"),
    ("f_physics_mech", "enve_air"),
    ("f_chem_general", "enve_solid_waste"),
    ("f_tech_writing", "enve_solid_waste"),
    ("adv_stats_eng", "enve_sustainability"),
    ("f_tech_writing", "enve_sustainability"),
    ("me_fluid", "enve_hydrology"),
    ("f_stats_basic", "enve_hydrology"),
    ("adv_diff_eq", "enve_hydrology"),
    ("f_stats_basic", "ie_ergonomics"),
    ("f_tech_writing", "ie_ergonomics"),
    ("f_tech_writing", "ie_work_study"),
    ("f_stats_basic", "ie_work_study"),
    ("adv_optimization", "ie_operations"),
    ("adv_stats_eng", "ie_operations"),
    ("adv_discrete", "ie_operations"),
    ("adv_stats_eng", "ie_quality"),
    ("f_stats_basic", "ie_quality"),
    ("adv_optimization", "ie_supply_chain"),
    ("adv_stats_eng", "ie_supply_chain"),
    ("adv_cad", "ie_facilities"),
    ("ie_work_study", "ie_facilities"),
    ("f_logic", "ie_systems_eng"),
    ("f_tech_writing", "ie_systems_eng"),
    ("ie_systems_eng", "ie_project_mgmt"),
    ("f_tech_writing", "ie_project_mgmt"),
    ("f_chem_general", "mat_structure"),
    ("f_physics_waves", "mat_structure"),
    ("f_calculus1", "mat_structure"),
    ("mat_structure", "mat_mechanical"),
    ("me_mechanics_mats", "mat_mechanical"),
    ("adv_stats_eng", "mat_mechanical"),
    ("mat_structure", "mat_processing"),
    ("me_manufacturing", "mat_processing"),
    ("mat_structure", "mat_electronic"),
    ("f_physics_waves", "mat_electronic"),
    ("adv_linear_alg", "mat_electronic"),
    ("mat_structure", "mat_characterization"),
    ("f_sci_method", "mat_characterization"),
    ("mat_mechanical", "mat_biomaterials"),
    ("f_bio_basic", "mat_biomaterials"),
    ("mat_structure", "mat_biomaterials"),
    ("f_physics_waves", "nuke_physics"),
    ("f_calculus2", "nuke_physics"),
    ("f_chem_general", "nuke_physics"),
    ("nuke_physics", "nuke_transport"),
    ("adv_diff_eq", "nuke_transport"),
    ("adv_numerical", "nuke_transport"),
    ("nuke_physics", "nuke_reactor"),
    ("nuke_transport", "nuke_reactor"),
    ("adv_numerical", "nuke_reactor"),
    ("me_fluid", "nuke_thermal"),
    ("me_heat_transfer", "nuke_thermal"),
    ("nuke_reactor", "nuke_thermal"),
    ("f_tech_writing", "nuke_safety"),
    ("adv_stats_eng", "nuke_safety"),
    ("nuke_reactor", "nuke_safety"),
    ("adv_linear_alg", "rob_kinematics"),
    ("me_dynamics", "rob_kinematics"),
    ("f_calculus1", "rob_kinematics"),
    ("rob_kinematics", "rob_dynamics_ctrl"),
    ("adv_diff_eq", "rob_dynamics_ctrl"),
    ("ee_control", "rob_dynamics_ctrl"),
    ("adv_prog_eng", "rob_perception"),
    ("adv_linear_alg", "rob_perception"),
    ("ee_signals", "rob_perception"),
    ("rob_kinematics", "rob_planning"),
    ("adv_optimization", "rob_planning"),
    ("adv_discrete", "rob_planning"),
    ("ee_microcontrollers", "rob_actuators"),
    ("ee_electronics", "rob_actuators"),
    ("me_dynamics", "rob_actuators"),
    ("adv_prog_eng", "rob_ros"),
    ("rob_kinematics", "rob_ros"),
    ("rob_dynamics_ctrl", "rob_ros"),
    ("adv_numerical", "adv_fea"),
    ("adv_linear_alg", "adv_fea"),
    ("me_mechanics_mats", "adv_fea"),
    ("adv_numerical", "adv_cfd"),
    ("adv_multivariable", "adv_cfd"),
    ("me_fluid", "adv_cfd"),
    ("adv_diff_eq", "adv_systems_model"),
    ("adv_linear_alg", "adv_systems_model"),
    ("ee_control", "adv_systems_model"),
    ("adv_fea", "sp_mech_eng"),
    ("adv_cfd", "sp_mech_eng"),
    ("adv_systems_model", "sp_mech_eng"),
    ("me_statics", "sp_mech_eng"),
    ("me_dynamics", "sp_mech_eng"),
    ("me_mechanics_mats", "sp_mech_eng"),
    ("me_thermo", "sp_mech_eng"),
    ("me_fluid", "sp_mech_eng"),
    ("me_heat_transfer", "sp_mech_eng"),
    ("me_machine_design", "sp_mech_eng"),
    ("me_manufacturing", "sp_mfg_eng"),
    ("me_machine_design", "sp_mfg_eng"),
    ("ie_quality", "sp_mfg_eng"),
    ("ee_circuits", "sp_elec_eng"),
    ("ee_electronics", "sp_elec_eng"),
    ("ee_signals", "sp_elec_eng"),
    ("ee_power", "sp_elec_eng"),
    ("ee_control", "sp_elec_eng"),
    ("ee_electromagnetics", "sp_elec_eng"),
    ("adv_systems_model", "sp_elec_eng"),
    ("ee_digital", "sp_comp_eng"),
    ("ee_microcontrollers", "sp_comp_eng"),
    ("ee_vlsi", "sp_comp_eng"),
    ("adv_cpp", "sp_comp_eng"),
    ("ce_structural", "sp_civil_eng"),
    ("ce_geotech", "sp_civil_eng"),
    ("ce_hydraulics", "sp_civil_eng"),
    ("ce_transport", "sp_civil_eng"),
    ("ce_concrete", "sp_civil_eng"),
    ("adv_fea", "sp_civil_eng"),
    ("ce_steel", "sp_structural_eng"),
    ("ce_concrete", "sp_structural_eng"),
    ("ce_structural", "sp_structural_eng"),
    ("adv_fea", "sp_structural_eng"),
    ("che_mass_energy", "sp_chem_eng"),
    ("che_thermo", "sp_chem_eng"),
    ("che_transport", "sp_chem_eng"),
    ("che_kinetics", "sp_chem_eng"),
    ("che_separations", "sp_chem_eng"),
    ("che_process_design", "sp_chem_eng"),
    ("adv_cfd", "sp_chem_eng"),
    ("che_process_design", "sp_petroleum_eng"),
    ("che_thermo", "sp_petroleum_eng"),
    ("me_fluid", "sp_petroleum_eng"),
    ("aero_aero", "sp_aero_eng"),
    ("aero_flight_mech", "sp_aero_eng"),
    ("aero_propulsion", "sp_aero_eng"),
    ("aero_structures", "sp_aero_eng"),
    ("aero_orbital", "sp_aero_eng"),
    ("aero_avionics", "sp_aero_eng"),
    ("adv_fea", "sp_aero_eng"),
    ("adv_cfd", "sp_aero_eng"),
    ("adv_systems_model", "sp_aero_eng"),
    ("bme_physiology", "sp_bio_eng"),
    ("bme_biomechanics", "sp_bio_eng"),
    ("bme_bioinstrumentation", "sp_bio_eng"),
    ("bme_biomaterials", "sp_bio_eng"),
    ("bme_medical_imaging", "sp_bio_eng"),
    ("bme_reg_affairs", "sp_bio_eng"),
    ("adv_fea", "sp_bio_eng"),
    ("enve_water", "sp_env_eng"),
    ("enve_air", "sp_env_eng"),
    ("enve_solid_waste", "sp_env_eng"),
    ("enve_sustainability", "sp_env_eng"),
    ("enve_hydrology", "sp_env_eng"),
    ("adv_cfd", "sp_env_eng"),
    ("ie_operations", "sp_industrial_eng"),
    ("ie_quality", "sp_industrial_eng"),
    ("ie_supply_chain", "sp_industrial_eng"),
    ("ie_ergonomics", "sp_industrial_eng"),
    ("ie_systems_eng", "sp_industrial_eng"),
    ("ie_project_mgmt", "sp_industrial_eng"),
    ("mat_structure", "sp_materials_sci"),
    ("mat_mechanical", "sp_materials_sci"),
    ("mat_processing", "sp_materials_sci"),
    ("mat_electronic", "sp_materials_sci"),
    ("mat_characterization", "sp_materials_sci"),
    ("adv_fea", "sp_materials_sci"),
    ("nuke_physics", "sp_nuclear_eng"),
    ("nuke_transport", "sp_nuclear_eng"),
    ("nuke_reactor", "sp_nuclear_eng"),
    ("nuke_thermal", "sp_nuclear_eng"),
    ("nuke_safety", "sp_nuclear_eng"),
    ("rob_kinematics", "sp_robotics_eng"),
    ("rob_dynamics_ctrl", "sp_robotics_eng"),
    ("rob_perception", "sp_robotics_eng"),
    ("rob_planning", "sp_robotics_eng"),
    ("rob_actuators", "sp_robotics_eng"),
    ("rob_ros", "sp_robotics_eng"),
    ("adv_systems_model", "sp_robotics_eng"),
    ("sp_mech_eng", "hub_bs_eng"),
    ("sp_elec_eng", "hub_bs_eng"),
    ("sp_comp_eng", "hub_bs_eng"),
    ("sp_civil_eng", "hub_bs_eng"),
    ("sp_structural_eng", "hub_bs_eng"),
    ("sp_chem_eng", "hub_bs_eng"),
    ("sp_aero_eng", "hub_bs_eng"),
    ("sp_bio_eng", "hub_bs_eng"),
    ("sp_env_eng", "hub_bs_eng"),
    ("sp_industrial_eng", "hub_bs_eng"),
    ("sp_materials_sci", "hub_bs_eng"),
    ("sp_nuclear_eng", "hub_bs_eng"),
    ("sp_robotics_eng", "hub_bs_eng"),
    ("sp_mfg_eng", "hub_bs_eng"),
    ("sp_petroleum_eng", "hub_bs_eng"),
    ("sp_mech_eng", "hub_ms_eng"),
    ("sp_elec_eng", "hub_ms_eng"),
    ("sp_civil_eng", "hub_ms_eng"),
    ("sp_structural_eng", "hub_ms_eng"),
    ("sp_chem_eng", "hub_ms_eng"),
    ("sp_aero_eng", "hub_ms_eng"),
    ("sp_bio_eng", "hub_ms_eng"),
    ("sp_nuclear_eng", "hub_ms_eng"),
    ("sp_robotics_eng", "hub_ms_eng"),
    ("sp_materials_sci", "hub_ms_eng"),
    ("sp_mech_eng", "hub_phd_eng"),
    ("sp_elec_eng", "hub_phd_eng"),
    ("sp_chem_eng", "hub_phd_eng"),
    ("sp_aero_eng", "hub_phd_eng"),
    ("sp_bio_eng", "hub_phd_eng"),
    ("sp_nuclear_eng", "hub_phd_eng"),
    ("sp_materials_sci", "hub_phd_eng"),
    ("sp_robotics_eng", "hub_phd_eng"),
    ("hub_bs_eng", "hub_pe_license"),
    ("sp_industrial_eng", "hub_cert_eng"),
    ("sp_mfg_eng", "hub_cert_eng"),
    ("sp_civil_eng", "hub_cert_eng"),
    ("hub_bs_eng", "car_mech_eng"),
    ("hub_bs_eng", "car_thermal_eng"),
    ("hub_bs_eng", "car_mfg_eng"),
    ("hub_bs_eng", "car_automotive_eng"),
    ("hub_bs_eng", "car_product_dev"),
    ("hub_bs_eng", "car_elec_eng"),
    ("hub_bs_eng", "car_power_eng"),
    ("hub_bs_eng", "car_controls_eng"),
    ("hub_bs_eng", "car_rf_eng"),
    ("hub_bs_eng", "car_ic_designer"),
    ("hub_ms_eng", "car_ic_designer"),
    ("hub_bs_eng", "car_embedded_eng"),
    ("hub_bs_eng", "car_avionics_eng"),
    ("hub_bs_eng", "car_civil_eng"),
    ("hub_pe_license", "car_civil_eng"),
    ("hub_bs_eng", "car_struct_eng"),
    ("hub_pe_license", "car_struct_eng"),
    ("hub_bs_eng", "car_geotechnical"),
    ("hub_bs_eng", "car_transport_eng"),
    ("hub_bs_eng", "car_water_resources"),
    ("hub_bs_eng", "car_chem_eng"),
    ("hub_bs_eng", "car_process_eng"),
    ("hub_bs_eng", "car_process_safety"),
    ("hub_bs_eng", "car_pharma_mfg"),
    ("hub_bs_eng", "car_petroleum_eng"),
    ("hub_bs_eng", "car_aero_eng"),
    ("hub_bs_eng", "car_propulsion_eng"),
    ("hub_bs_eng", "car_flight_test"),
    ("hub_bs_eng", "car_spacecraft_eng"),
    ("hub_bs_eng", "car_guidance_nav"),
    ("hub_ms_eng", "car_guidance_nav"),
    ("hub_bs_eng", "car_bme_eng"),
    ("hub_bs_eng", "car_medical_device"),
    ("hub_bs_eng", "car_clinical_eng"),
    ("hub_ms_eng", "car_imaging_scientist"),
    ("hub_ms_eng", "car_tissue_eng"),
    ("hub_phd_eng", "car_tissue_eng"),
    ("hub_bs_eng", "car_env_eng"),
    ("hub_bs_eng", "car_sustainability"),
    ("hub_bs_eng", "car_remediation"),
    ("hub_bs_eng", "car_water_eng"),
    ("hub_bs_eng", "car_industrial_eng"),
    ("hub_bs_eng", "car_process_imp"),
    ("hub_bs_eng", "car_supply_chain_eng"),
    ("hub_bs_eng", "car_quality_eng"),
    ("hub_cert_eng", "car_quality_eng"),
    ("hub_bs_eng", "car_systems_eng"),
    ("hub_ms_eng", "car_systems_eng"),
    ("hub_bs_eng", "car_project_eng"),
    ("hub_bs_eng", "car_materials_eng"),
    ("hub_bs_eng", "car_metallurgist"),
    ("hub_bs_eng", "car_composites_eng"),
    ("hub_bs_eng", "car_semiconductor"),
    ("hub_ms_eng", "car_semiconductor"),
    ("hub_bs_eng", "car_nuclear_eng"),
    ("hub_bs_eng", "car_radiation_safety"),
    ("hub_ms_eng", "car_fusion_eng"),
    ("hub_phd_eng", "car_fusion_eng"),
    ("hub_bs_eng", "car_robotics_eng"),
    ("hub_bs_eng", "car_mechatronics"),
    ("hub_ms_eng", "car_autonomy_eng"),
    ("hub_phd_eng", "car_autonomy_eng"),
    ("hub_ms_eng", "car_research_eng"),
    ("hub_phd_eng", "car_research_eng"),
    ("hub_phd_eng", "car_professor"),
    ("hub_bs_eng", "car_tech_consultant"),
    ("hub_ms_eng", "car_tech_consultant"),
]


def seed():
    try:
        cat_rows = [
            {"code": c[0], "name": c[1], "color": c[2], "sort_order": c[3]}
            for c in CATEGORIES
        ]
        supabase.table("categories").insert(cat_rows).execute()

        node_rows = [
            {
                "id": n[0],
                "name": n[1],
                "tier": n[2],
                "cat": n[3],
                "hrs": n[4],
                "asmt_count": n[5],
                "edu_level": n[6],
                "summary": n[7],
                "mastery": n[8],
            }
            for n in NODES
        ]
        supabase.table("skill_nodes").insert(node_rows).execute()

        edge_rows = [{"from_id": e[0], "to_id": e[1]} for e in EDGES]
        supabase.table("skill_edges").insert(edge_rows).execute()

        print(f"Seeded {len(CATEGORIES)} categories, {len(NODES)} nodes, and {len(EDGES)} edges successfully.")
    except Exception as e:
        print(f"Seed failed: {e}")
        raise


if __name__ == "__main__":
    seed()
